# bucles
""" En python existen 3 tipos de bucles: """
# 1. for
# 2. while
# 3. do-while

# for
# El bucle for se utiliza para iterar sobre una secuencia de elementos, como una lista, tupla, diccionario, conjunto o cualquier otro tipo de iterable
# La sintaxis del bucle for es la siguiente:
# for variable in iterable:
#     bloque de codigo

# Ejemplo de bucle for para iterar sobre una lista de frutas
fruits = ["manzana", "banana", "pera", "naranja"]

for fruit in fruits:
    print("La fruta es:",fruit)